---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: operator-serviceaccount
    namespace: guestbook
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: operator
  labels:
    name: operator
spec:
  containers:
    - name: myapp
      image: operator:v1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      imagePullPolicy: Never
  serviceAccountName: operator-serviceaccount
